"""Add plan field

Revision ID: 18ba451cdacc
Revises: 9a3b7f36274e
Create Date: 2026-01-29 13:08:56.286146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ba451cdacc'
down_revision: Union[str, Sequence[str], None] = '9a3b7f36274e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('plan', sa.String(), nullable=True))
    op.alter_column('payment_transactions', 'transaction_signature',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_transactions', 'transaction_signature',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('payment_transactions', 'plan')
    # ### end Alembic commands ###
