"""add_summary_style

Revision ID: 2f36ad567c41
Revises: da74296d45b0
Create Date: 2026-01-27 14:13:13.614766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f36ad567c41'
down_revision: Union[str, Sequence[str], None] = 'da74296d45b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('summary_style', sa.String(), server_default='short', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'summary_style')
    # ### end Alembic commands ###
