"""add_usage_limits

Revision ID: 89bdb6db4286
Revises: 18ba451cdacc
Create Date: 2026-01-29 17:25:16.078175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bdb6db4286'
down_revision: Union[str, Sequence[str], None] = '18ba451cdacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_news_refresh_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_summary_refresh_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_summary_refresh_date')
    op.drop_column('users', 'last_news_refresh_date')
    op.drop_column('users', 'refresh_tokens')
    # ### end Alembic commands ###
