"""Add sender_address to payment_transactions

Revision ID: 9a3b7f36274e
Revises: 2f36ad567c41
Create Date: 2026-01-28 21:34:26.249733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3b7f36274e'
down_revision: Union[str, Sequence[str], None] = '2f36ad567c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('sender_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_transactions', 'sender_address')
    # ### end Alembic commands ###
