"""update_subscription_fk_ondelete

Revision ID: d61aada91422
Revises: 89bdb6db4286
Create Date: 2026-01-29 18:31:38.543443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd61aada91422'
down_revision: Union[str, Sequence[str], None] = '89bdb6db4286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subscriptions_transaction_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'payment_transactions', ['transaction_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_transaction_id_fkey'), 'subscriptions', 'payment_transactions', ['transaction_id'], ['id'])
    # ### end Alembic commands ###
