"""Add plan fields fixed

Revision ID: f6dd189f2dd9
Revises: c1a2b3d4e5f6
Create Date: 2026-02-12 10:30:57.290127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6dd189f2dd9'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan_type', sa.String(), server_default=sa.text("'free'"), nullable=False))
    op.add_column('users', sa.Column('trial_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('trial_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deep_analysis_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('deep_analysis_last_reset', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deep_analysis_last_reset')
    op.drop_column('users', 'deep_analysis_count')
    op.drop_column('users', 'trial_end_date')
    op.drop_column('users', 'trial_start_date')
    op.drop_column('users', 'plan_type')
    # ### end Alembic commands ###
